/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenshotDetectorRouteImport } from './routes/screenshot-detector'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DnaMapRouteImport } from './routes/dna-map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ScreenshotDetectorRoute = ScreenshotDetectorRouteImport.update({
  id: '/screenshot-detector',
  path: '/screenshot-detector',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaMapRoute = DnaMapRouteImport.update({
  id: '/dna-map',
  path: '/dna-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dna-map': typeof DnaMapRoute
  '/emergency': typeof EmergencyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/screenshot-detector': typeof ScreenshotDetectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dna-map': typeof DnaMapRoute
  '/emergency': typeof EmergencyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/screenshot-detector': typeof ScreenshotDetectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dna-map': typeof DnaMapRoute
  '/emergency': typeof EmergencyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/screenshot-detector': typeof ScreenshotDetectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/dna-map'
    | '/emergency'
    | '/profile'
    | '/reports'
    | '/screenshot-detector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/dna-map'
    | '/emergency'
    | '/profile'
    | '/reports'
    | '/screenshot-detector'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/dna-map'
    | '/emergency'
    | '/profile'
    | '/reports'
    | '/screenshot-detector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  DnaMapRoute: typeof DnaMapRoute
  EmergencyRoute: typeof EmergencyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ScreenshotDetectorRoute: typeof ScreenshotDetectorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screenshot-detector': {
      id: '/screenshot-detector'
      path: '/screenshot-detector'
      fullPath: '/screenshot-detector'
      preLoaderRoute: typeof ScreenshotDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna-map': {
      id: '/dna-map'
      path: '/dna-map'
      fullPath: '/dna-map'
      preLoaderRoute: typeof DnaMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  DnaMapRoute: DnaMapRoute,
  EmergencyRoute: EmergencyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ScreenshotDetectorRoute: ScreenshotDetectorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
